# Generated by Django 5.2.5 on 2025-08-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_student_school_alter_teacher_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='location',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='location',
        ),
        migrations.AddField(
            model_name='school',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
