# Generated by Django 5.2.5 on 2025-08-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_school_location_remove_teacher_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
