# Generated by Django 5.2.5 on 2025-08-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_teacher_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('system_admin', 'System Admin'), ('teacher', 'Teacher'), ('student', 'Student')], max_length=20, null=True),
        ),
    ]
