# Generated by Django 5.2.5 on 2025-08-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_national_id_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('system_admin', 'System Admin'), ('teacher', 'Teacher'), ('student', 'Student')], max_length=30, null=True),
        ),
    ]
