# Generated by Django 5.2.5 on 2025-08-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_exercise_last_updated_news_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
