# Generated by Django 5.2.5 on 2025-08-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_alter_exercise_title_alter_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
